apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mar21-rag-cibuild-gitops
  description: This is GitOps manifest for mar21-rag-cibuild   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=mar21-rag-cibuild
    janus-idp.io/tekton: mar21-rag-cibuild 
    backstage.io/kubernetes-id: mar21-rag-cibuild 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mar21-rag-cibuild  
