apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: mar21-rag-cibuild
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar21-rag-cibuild
  name: mar21-rag-cibuild
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mar21-rag-cibuild
    weight: 100
  wildcardPolicy: None
