apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mar21-rag-cibuild
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar21-rag-cibuild
  name: mar21-rag-cibuild
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: mar21-rag-cibuild
